using CommandLine;
using RCPA.Commandline;
using System.IO;

namespace CQS.Genome.Vcf
{
  public class VcfSlimProcessorOptions : AbstractOptions
  {
    public VcfSlimProcessorOptions()
    { }

    [Option('i', "input", Required = true, MetaValue = "FILE", HelpText = "Input vcf file")]
    public string InputFile { get; set; }

    [Option('o', "output", Required = true, MetaValue = "FILE", HelpText = "Output vcf file")]
    public string OutputFile { get; set; }

    [Option('d', "dictFile", Required = true, MetaValue = "FILE", HelpText = "Genome dict file generated by picard")]
    public string DictFile { get; set; }

    public override bool PrepareOptions()
    {
      if (!File.Exists(this.InputFile))
      {
        ParsingErrors.Add(string.Format("Input file not exists {0}.", this.InputFile));
      }

      if (!File.Exists(this.DictFile))
      {
        ParsingErrors.Add(string.Format("Geome dict file not exists {0}.", this.DictFile));
      }

      return ParsingErrors.Count == 0;
    }
  }
}
