using CommandLine;
using RCPA.Commandline;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace CQS.Genome.Parclip
{
  public class ParclipMiRNATargetBuilderOptions : AbstractTargetBuilderOptions
  {
    private const int DEFAULT_SEED_LENGTH = 6;

    public ParclipMiRNATargetBuilderOptions()
    {
      this.SeedLength = DEFAULT_SEED_LENGTH;
    }

    /// <summary>
    /// T2C xml file generated by SmallRNA T2C Builder
    /// </summary>
    [Option('i', "inputFile", Required = true, MetaValue = "FILE", HelpText = "T2C xml file generated by SmallRNA T2C Builder")]
    public string InputFile { get; set; }

    /// <summary>
    /// Seed length of miRNA, default=6
    /// </summary>
    [Option('s', "seedLength", Required = false, DefaultValue = DEFAULT_SEED_LENGTH, MetaValue = "DOUBLE", HelpText = "Seed length of miRNA")]
    public int SeedLength { get; set; }

    public override bool PrepareOptions()
    {
      base.PrepareOptions();

      if (!File.Exists(this.InputFile))
      {
        ParsingErrors.Add(string.Format("Input T2C count xml file not exists {0}.", this.InputFile));
      }

      return ParsingErrors.Count == 0;
    }
  }
}
