using CommandLine;
using RCPA.Commandline;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace CQS.Genome.Parclip
{
  public class SeedTargetBuilderOptions : AbstractTargetBuilderOptions
  {
    public SeedTargetBuilderOptions() { }

    /// <summary>
    /// T2C xml file generated by SmallRNA T2C Builder
    /// </summary>
    [Option('i', "inputFile", Required = true, MetaValue = "FILE", HelpText = "Seed file, each line include one seed")]
    public string InputFile { get; set; }

    public override bool PrepareOptions()
    {
      base.PrepareOptions();

      if (!File.Exists(this.InputFile))
      {
        ParsingErrors.Add(string.Format("Input seed file not exists {0}.", this.InputFile));
      }

      return ParsingErrors.Count == 0;
    }
  }
}
