using CommandLine;
using RCPA.Commandline;
using System.IO;

namespace CQS.Genome.SmallRNA
{
  public class TrnaNonTemplatedNucleotideAdditionsQueryBuilderOptions : AbstractOptions
  {
    private const int DEFAULT_MinimumReadLength = 25;

    public TrnaNonTemplatedNucleotideAdditionsQueryBuilderOptions()
    { }

    [Option('l', "minlen", MetaValue = "INT", DefaultValue = DEFAULT_MinimumReadLength, HelpText = "Minimum read length")]
    public int MinimumReadLength { get; set; }

    [Option('i', "inputFile", Required = true, MetaValue = "FILE", HelpText = "Fastq file")]
    public string InputFile { get; set; }

    [Option("ccaFile", Required = true, MetaValue = "FILE", HelpText = "CCA file generated by check_cca")]
    public string CCAFile { get; set; }

    [Option('c', "countFile", Required = false, MetaValue = "FILE", HelpText = "Sequence/count file")]
    public string CountFile { get; set; }

    [Option('o', "outputFile", Required = true, MetaValue = "FILE", HelpText = "Output fastq file")]
    public string OutputFile { get; set; }

    [Option('s', "summaryFile", Required = true, MetaValue = "FILE", HelpText = "Output summary file")]
    public string SummaryFile { get; set; }

    public override bool PrepareOptions()
    {
      if (!File.Exists(this.InputFile))
      {
        ParsingErrors.Add(string.Format("Input file not exists {0}.", this.InputFile));
        return false;
      }

      if (!File.Exists(this.CCAFile))
      {
        ParsingErrors.Add(string.Format("CCA file not exists {0}.", this.CCAFile));
        return false;
      }

      if (!string.IsNullOrEmpty(this.CountFile) && !File.Exists(this.CountFile))
      {
        ParsingErrors.Add(string.Format("Count file not exists {0}.", this.CountFile));
        return false;
      }

      return true;
    }

    private SmallRNACountMap cm;

    public virtual SmallRNACountMap GetCountMap()
    {
      if (cm == null)
      {
        cm = new SmallRNACountMap(this.CountFile);
      }
      return cm;
    }
  }
}

